### ISSUE TITLE
problems when tesing

### ISSUE THREAD

**Issue by Xiaofeng-life** [clks-wzz/FAS-SGTD#18]
Hello. I have a problem when testing, error is as follows:
Traceback (most recent call last):
  File "test_test.py", line 272, in <module>
    offline_eval()
  File "test_test.py", line 264, in offline_eval
    officialEval(os.path.join(flags.path.model, 'model.ckpt-%d'%(iter_now)))
  File "test_test.py", line 198, in officialEval
    officialEvalSub(path_txt_test, [flags.path.test_file], 'test', path_model_now)   
  File "test_test.py", line 186, in officialEvalSub
    video_score_mean = video_score/video_frame_count
ZeroDivisionError: float division by zero

**Comment by clks-wzz** [comment]
"video_frame_count" is zero. You should adjust the test file to your own style.

**Comment by haiderasad** [comment]
how to add test file and where in test.py? should update documentation
